"""Flutter / Dart code generator.

Hero target. Produces a runnable Flutter app:

- `lib/main.dart` — `MaterialApp` with `ColorScheme.fromSeed` keyed off the
  extracted theme, named routes for every screen, and Navigator wiring for
  every `tap` interaction.
- `lib/screens/<name>_screen.dart` — one `StatelessWidget` per `Screen`.
- `lib/widgets/shared.dart` — repeated subtrees hoisted into shared widgets.
- `pubspec.yaml` — minimum runnable manifest.
"""

from __future__ import annotations

from dataclasses import dataclass

from mimic.codegen._dedup import DedupResult, SharedComponent, analyze
from mimic.codegen._icons import flutter_icon
from mimic.codegen.base import GeneratedFile, Target
from mimic.models import Screen, Style, WidgetNode, WidgetTree
from mimic.theme import Theme
from mimic.theme import extract as extract_theme

_KIND_MAP: dict[str, str] = {
    "container": "Container",
    "row": "Row",
    "column": "Column",
    "stack": "Stack",
    "text": "Text",
    "image": "Image.network",
    "icon": "Icon",
    "button": "ElevatedButton",
    "text_field": "TextField",
    "checkbox": "Checkbox",
    "switch": "Switch",
    "slider": "Slider",
    "list": "ListView",
    "list_item": "ListTile",
    "card": "Card",
    "app_bar": "AppBar",
    "fab": "FloatingActionButton",
    "scroll_view": "SingleChildScrollView",
    "spacer": "Spacer",
    "divider": "Divider",
    "tab_bar": "TabBar",
    "bottom_nav": "BottomNavigationBar",
}


@dataclass
class _Ctx:
    theme: Theme
    tree: WidgetTree
    dedup: DedupResult
    interactions: dict[str, str]  # source_widget_id -> target_screen_id


class FlutterGenerator:
    target: Target = "flutter"

    def generate(self, tree: WidgetTree) -> list[GeneratedFile]:
        theme = extract_theme(tree)
        dedup = analyze(tree)
        interactions = {
            i.source_widget_id: i.target_screen_id
            for i in tree.interactions
            if i.kind == "tap" and i.target_screen_id
        }
        ctx = _Ctx(theme=theme, tree=tree, dedup=dedup, interactions=interactions)

        files: list[GeneratedFile] = [
            GeneratedFile("lib/main.dart", _emit_main(ctx), "dart"),
            GeneratedFile("pubspec.yaml", _emit_pubspec(), "yaml"),
        ]
        for screen in tree.screens:
            files.append(
                GeneratedFile(
                    f"lib/screens/{_snake(screen.name)}_screen.dart",
                    _emit_screen(screen, ctx),
                    "dart",
                )
            )
        if dedup.shared:
            files.append(GeneratedFile("lib/widgets/shared.dart", _emit_shared(ctx), "dart"))
        return files


def _emit_main(ctx: _Ctx) -> str:
    initial = ctx.tree.initial_screen
    imports = "\n".join(f"import 'screens/{_snake(s.name)}_screen.dart';" for s in ctx.tree.screens)
    routes_inner = ",\n".join(
        f'        "{_route(s)}": (context) => const {_class(s)}()' for s in ctx.tree.screens
    )
    seed = ctx.theme.primary or ctx.theme.background or "#6E56CF"
    return f"""import 'package:flutter/material.dart';
{imports}

void main() => runApp(const MimicApp());

class MimicApp extends StatelessWidget {{
  const MimicApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: 'Generated by mimic',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: {_color(seed)},
          brightness: Brightness.light,
        ),
      ),
      initialRoute: '/',
      routes: {{
        '/': (context) => const {_class(initial)}(),
{routes_inner},
      }},
    );
  }}
}}
"""


def _emit_screen(screen: Screen, ctx: _Ctx) -> str:
    class_name = _class(screen)
    body = _emit_widget(screen.root, ctx, indent=10)
    bg = screen.background_color or ctx.theme.background or "#FFFFFF"
    return f"""import 'package:flutter/material.dart';

import '../widgets/shared.dart';

class {class_name} extends StatelessWidget {{
  const {class_name}({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      backgroundColor: {_color(bg)},
      body: SafeArea(
        child:
{body},
      ),
    );
  }}
}}
"""


def _emit_shared(ctx: _Ctx) -> str:
    parts: list[str] = ["import 'package:flutter/material.dart';\n"]
    for shared in ctx.dedup.shared:
        slot_lookup = {(s.path, s.kind): s.name for s in shared.slots}
        body = _emit_widget(
            shared.template, ctx, indent=6, in_shared=shared,
            path=(), slot_lookup=slot_lookup,
        )
        ctor_params = ", ".join(
            f"required this.{slot.name}" for slot in shared.slots
        )
        ctor_args = (
            "{" + ("super.key, " + ctor_params if ctor_params else "super.key") + "}"
        )
        field_decls = (
            "\n  ".join(f"final String {slot.name};" for slot in shared.slots)
            if shared.slots
            else ""
        )
        const_kw = "const " if not shared.slots else ""
        parts.append(
            f"""class {shared.name} extends StatelessWidget {{
  {const_kw}{shared.name}({ctor_args});

  {field_decls}

  @override
  Widget build(BuildContext context) {{
    return
{body};
  }}
}}
"""
        )
    return "\n".join(parts)


def _emit_widget(
    node:        WidgetNode,
    ctx:         _Ctx,
    indent:      int = 0,
    in_shared:   SharedComponent | None = None,
    path:        tuple[int, ...] = (),
    slot_lookup: dict[tuple[tuple[int, ...], str], str] | None = None,
) -> str:
    pad = " " * indent

    if in_shared is None:
        component = ctx.dedup.component_for(node.id)
        if component:
            if not component.slots:
                return f"{pad}const {component.name}()"
            args = ", ".join(
                f'{slot.name}: "{_escape(component.bindings[node.id].get(slot.name, ""))}"'
                for slot in component.slots
            )
            return f"{pad}{component.name}({args})"

    cls = _KIND_MAP.get(node.kind, "Container")
    args: list[str] = []

    def _slot(kind: str) -> str | None:
        if slot_lookup is None:
            return None
        return slot_lookup.get((path, kind))

    def _str_lit(value: str, kind: str, *, const: bool = True) -> str:
        """Dart string expression — slot reference when shared, literal otherwise."""
        s = _slot(kind)
        if s is not None:
            return s
        prefix = "const " if const else ""
        return f'{prefix}"{_escape(value)}"' if not const else f'"{_escape(value)}"'

    if node.kind == "text" and node.text is not None:
        args.append(_str_lit(node.text, "text"))
        style = _text_style(node.style)
        if style:
            args.append(f"style: {style}")

    elif node.kind == "button":
        button_cls = _material3_button(node)
        cls = button_cls
        label = node.text or "Button"
        on_press = ctx.interactions.get(node.id)
        on_pressed = f'() => Navigator.pushNamed(context, "/{on_press}")' if on_press else "() {}"

        if button_cls == "IconButton":
            icon = flutter_icon(node.icon_name or "circle")
            args = [
                f"onPressed: {on_pressed}",
                f"icon: const Icon(Icons.{icon})",
            ]
            if node.style.foreground_color:
                args.append(f"color: {_color(node.style.foreground_color)}")
        else:
            args.append(f"onPressed: {on_pressed}")
            bg = node.style.background_color
            fg = node.style.foreground_color
            if button_cls in {"FilledButton", "ElevatedButton"} and (bg or fg):
                style_parts: list[str] = []
                if bg:
                    style_parts.append(f"backgroundColor: {_color(bg)}")
                if fg:
                    style_parts.append(f"foregroundColor: {_color(fg)}")
                args.append(f"style: {button_cls}.styleFrom({', '.join(style_parts)})")
            elif button_cls == "OutlinedButton" and node.style.border_color:
                args.append(
                    f"style: OutlinedButton.styleFrom("
                    f"side: BorderSide(color: {_color(node.style.border_color)}))"
                )
            slot = _slot("text")
            text_arg = slot if slot else f'"{_escape(label)}"'
            args.append(f"child: Text({text_arg})")

    elif node.kind == "text_field" and node.placeholder:
        ph_slot = _slot("placeholder")
        if ph_slot:
            args.append(
                f"decoration: InputDecoration("
                f"hintText: {ph_slot}, border: const OutlineInputBorder())"
            )
        else:
            args.append(
                f"decoration: const InputDecoration("
                f'hintText: "{_escape(node.placeholder)}", border: OutlineInputBorder())'
            )

    elif node.kind == "icon" and node.icon_name:
        args = [f"Icons.{flutter_icon(node.icon_name)}"]  # icon name slot unsupported in v0.3
        if node.style.font_size is not None:
            args.append(f"size: {node.style.font_size}")
        if node.style.foreground_color:
            args.append(f"color: {_color(node.style.foreground_color)}")

    elif node.kind == "image" and node.image_url:
        img_slot = _slot("image")
        args = [img_slot if img_slot else f'"{_escape(node.image_url)}"']

    elif node.kind == "switch":
        args = ["value: true", "onChanged: (_) {}"]

    elif node.kind == "checkbox":
        args = ["value: false", "onChanged: (_) {}"]

    elif node.kind == "fab":
        on_press = ctx.interactions.get(node.id)
        if on_press:
            args.append(f'onPressed: () => Navigator.pushNamed(context, "/{on_press}")')
        else:
            args.append("onPressed: () {}")
        icon = flutter_icon(node.icon_name or "add")
        args.append(f"child: const Icon(Icons.{icon})")
        if node.style.background_color:
            args.append(f"backgroundColor: {_color(node.style.background_color)}")

    elif node.kind == "list_item":
        on_tap = ctx.interactions.get(node.id)
        if node.text:
            slot = _slot("text")
            title_arg = slot if slot else f'"{_escape(node.text)}"'
            args.append(f"title: Text({title_arg})")
        if on_tap:
            args.append(f'onTap: () => Navigator.pushNamed(context, "/{on_tap}")')
        args.append("trailing: const Icon(Icons.chevron_right)")

    elif node.kind == "app_bar":
        if node.text:
            slot = _slot("text")
            title_arg = slot if slot else f'"{_escape(node.text)}"'
            args.append(f"title: Text({title_arg})")
        if node.style.background_color:
            args.append(f"backgroundColor: {_color(node.style.background_color)}")
        if node.style.foreground_color:
            args.append(f"foregroundColor: {_color(node.style.foreground_color)}")

    if node.children and node.kind in {"row", "column", "stack", "list"}:
        children = ",\n".join(
            _emit_widget(c, ctx, indent + 4, in_shared, (*path, i), slot_lookup)
            for i, c in enumerate(node.children)
        )
        args.append(f"children: [\n{children},\n{pad}]")
    elif node.children and node.kind in {"container", "card", "scroll_view"}:
        if len(node.children) == 1:
            args.append(
                "child: "
                + _emit_widget(
                    node.children[0], ctx, indent + 2, in_shared, (*path, 0), slot_lookup
                ).lstrip()
            )
        else:
            # Multi-child container/card → wrap children in a Column so we
            # don't silently drop content
            child_lines = ",\n".join(
                _emit_widget(c, ctx, indent + 6, in_shared, (*path, i), slot_lookup)
                for i, c in enumerate(node.children)
            )
            args.append(
                f"child: Column(\n"
                f"{pad}    crossAxisAlignment: CrossAxisAlignment.start,\n"
                f"{pad}    children: [\n{child_lines},\n{pad}    ],\n"
                f"{pad}  )"
            )

    if node.kind == "container":
        deco = _container_decoration(node.style)
        if deco:
            args.append(f"decoration: {deco}")
        pad_args = _padding(node.style)
        if pad_args:
            args.append(f"padding: const EdgeInsets.fromLTRB({pad_args})")

    if node.kind == "card":
        if node.style.background_color:
            args.append(f"color: {_color(node.style.background_color)}")
        if node.style.border_radius is not None:
            args.append(
                f"shape: RoundedRectangleBorder("
                f"borderRadius: BorderRadius.circular({node.style.border_radius}))"
            )

    body = ",\n".join(f"{pad}  {a}" for a in args)
    if not args:
        return f"{pad}{cls}()"
    return f"{pad}{cls}(\n{body},\n{pad})"


def _emit_pubspec() -> str:
    return """name: mimic_generated
description: Generated by mimic.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
"""


def _text_style(style: Style) -> str | None:
    parts: list[str] = []
    if style.font_size is not None:
        parts.append(f"fontSize: {style.font_size}")
    if style.font_weight in {"bold", "700", "800", "900"}:
        parts.append("fontWeight: FontWeight.bold")
    elif style.font_weight in {"500", "600", "medium", "semibold"}:
        parts.append("fontWeight: FontWeight.w600")
    if style.foreground_color:
        parts.append(f"color: {_color(style.foreground_color)}")
    return f"TextStyle({', '.join(parts)})" if parts else None


def _container_decoration(style: Style) -> str | None:
    parts: list[str] = []
    if style.background_color:
        parts.append(f"color: {_color(style.background_color)}")
    if style.border_radius is not None:
        parts.append(f"borderRadius: BorderRadius.circular({style.border_radius})")
    return f"BoxDecoration({', '.join(parts)})" if parts else None


def _padding(style: Style) -> str | None:
    if not style.padding:
        return None
    left, top, right, bottom = (
        style.padding[3],
        style.padding[0],
        style.padding[1],
        style.padding[2],
    )
    return f"{left}, {top}, {right}, {bottom}"


def _color(value: str) -> str:
    v = value.strip().lstrip("#")
    if v.lower() in {"transparent", "none"}:
        return "Colors.transparent"
    if v.startswith("0x") or len(v) in {6, 8}:
        hex_part = v.removeprefix("0x")
        if len(hex_part) == 6:
            hex_part = "FF" + hex_part
        return f"const Color(0x{hex_part.upper()})"
    return value


def _material3_button(node: WidgetNode) -> str:
    """Pick the Material 3 button variant that best matches the styling.

    Heuristics:
    - icon-only (no text + icon_name)               -> IconButton
    - no background, no border                      -> TextButton
    - border_color set, no background               -> OutlinedButton
    - background + shadow flag                      -> ElevatedButton
    - background, no shadow                         -> FilledButton (M3 default)
    """
    s = node.style
    has_bg = bool(s.background_color) and s.background_color not in {"transparent", "none"}
    has_border = bool(s.border_color)
    if not node.text and node.icon_name:
        return "IconButton"
    if not has_bg and has_border:
        return "OutlinedButton"
    if not has_bg and not has_border:
        return "TextButton"
    if has_bg and s.shadow:
        return "ElevatedButton"
    return "FilledButton"


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _snake(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower() if ch.isalnum() else "_")
    return "".join(out).strip("_") or "screen"


def _class(screen: Screen) -> str:
    parts = [p for p in screen.name.replace("-", "_").split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) + "Screen"


def _route(screen: Screen) -> str:
    return "/" + screen.id
