"""Flutter / Dart code generator.

Hero target. Walks the WidgetTree and emits a runnable Flutter app: one screen
file per `Screen`, a router stub when there are multiple screens, and a
`main.dart` entry point.
"""

from __future__ import annotations

from mimic.codegen.base import GeneratedFile, Target
from mimic.models import Screen, Style, WidgetNode, WidgetTree

_FLUTTER_KIND_MAP: dict[str, str] = {
    "container":  "Container",
    "row":        "Row",
    "column":     "Column",
    "stack":      "Stack",
    "text":       "Text",
    "image":      "Image.network",
    "icon":       "Icon",
    "button":     "ElevatedButton",
    "text_field": "TextField",
    "checkbox":   "Checkbox",
    "switch":     "Switch",
    "slider":     "Slider",
    "list":       "ListView",
    "list_item":  "ListTile",
    "card":       "Card",
    "app_bar":    "AppBar",
    "fab":        "FloatingActionButton",
    "scroll_view":"SingleChildScrollView",
    "spacer":     "Spacer",
    "divider":    "Divider",
    "tab_bar":    "TabBar",
    "bottom_nav": "BottomNavigationBar",
}


class FlutterGenerator:
    target: Target = "flutter"

    def generate(self, tree: WidgetTree) -> list[GeneratedFile]:
        files: list[GeneratedFile] = [
            GeneratedFile("lib/main.dart", _emit_main(tree), "dart"),
        ]
        for screen in tree.screens:
            files.append(
                GeneratedFile(
                    f"lib/screens/{_snake(screen.name)}_screen.dart",
                    _emit_screen(screen),
                    "dart",
                )
            )
        files.append(GeneratedFile("pubspec.yaml", _emit_pubspec(), "yaml"))
        return files


def _emit_main(tree: WidgetTree) -> str:
    initial = _snake(tree.initial_screen.name) + "_screen.dart"
    initial_class = _pascal(tree.initial_screen.name) + "Screen"
    imports = "\n".join(
        f"import 'screens/{_snake(s.name)}_screen.dart';" for s in tree.screens
    )
    return f"""import 'package:flutter/material.dart';
{imports}

void main() => runApp(const MimicApp());

class MimicApp extends StatelessWidget {{
  const MimicApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      title: 'Generated by mimic',
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.blue),
      home: const {initial_class}(),
    );
  }}
}}
"""


def _emit_screen(screen: Screen) -> str:
    class_name = _pascal(screen.name) + "Screen"
    body = _emit_widget(screen.root, indent=10)
    bg = screen.background_color or "Colors.white"
    return f"""import 'package:flutter/material.dart';

class {class_name} extends StatelessWidget {{
  const {class_name}({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      backgroundColor: {_color(bg)},
      body: SafeArea(
        child:
{body},
      ),
    );
  }}
}}
"""


def _emit_widget(node: WidgetNode, indent: int = 0) -> str:
    pad = " " * indent
    cls = _FLUTTER_KIND_MAP.get(node.kind, "Container")
    args: list[str] = []

    if node.kind == "text" and node.text is not None:
        args.append(f'"{_escape(node.text)}"')
        style = _text_style(node.style)
        if style:
            args.append(f"style: {style}")
    elif node.kind == "button":
        label = node.text or "Button"
        args.append("onPressed: () {}")
        args.append(f'child: const Text("{_escape(label)}")')
    elif node.kind == "text_field" and node.placeholder:
        args.append(
            f'decoration: const InputDecoration(hintText: "{_escape(node.placeholder)}")'
        )
    elif node.kind == "icon" and node.icon_name:
        args = [f"Icons.{_safe_icon(node.icon_name)}"]
    elif node.kind == "image" and node.image_url:
        args = [f'"{_escape(node.image_url)}"']

    if node.children and node.kind in {"row", "column", "stack", "list"}:
        children = ",\n".join(
            _emit_widget(c, indent + 4) for c in node.children
        )
        args.append(f"children: [\n{children},\n{pad}]")
    elif node.children and node.kind in {"container", "card", "scroll_view"}:
        args.append("child: " + _emit_widget(node.children[0], indent + 2).lstrip())

    if node.kind == "container":
        deco = _container_decoration(node.style)
        if deco:
            args.append(f"decoration: {deco}")

    body = ",\n".join(f"{pad}  {a}" for a in args)
    if not args:
        return f"{pad}{cls}()"
    return f"{pad}{cls}(\n{body},\n{pad})"


def _emit_pubspec() -> str:
    return """name: mimic_generated
description: Generated by mimic.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
"""


def _text_style(style: Style) -> str | None:
    parts: list[str] = []
    if style.font_size is not None:
        parts.append(f"fontSize: {style.font_size}")
    if style.font_weight in {"bold", "700", "800", "900"}:
        parts.append("fontWeight: FontWeight.bold")
    if style.foreground_color:
        parts.append(f"color: {_color(style.foreground_color)}")
    return f"TextStyle({', '.join(parts)})" if parts else None


def _container_decoration(style: Style) -> str | None:
    parts: list[str] = []
    if style.background_color:
        parts.append(f"color: {_color(style.background_color)}")
    if style.border_radius is not None:
        parts.append(f"borderRadius: BorderRadius.circular({style.border_radius})")
    return f"BoxDecoration({', '.join(parts)})" if parts else None


def _color(value: str) -> str:
    v = value.strip().lstrip("#")
    if v.lower() in {"transparent", "none"}:
        return "Colors.transparent"
    if v.startswith("0x") or len(v) in {6, 8}:
        hex_part = v.removeprefix("0x")
        if len(hex_part) == 6:
            hex_part = "FF" + hex_part
        return f"const Color(0x{hex_part.upper()})"
    return value


def _safe_icon(name: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in name).lower().strip("_") or "circle"


def _escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _snake(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower() if ch.isalnum() else "_")
    return "".join(out).strip("_") or "screen"


def _pascal(name: str) -> str:
    parts = [p for p in name.replace("-", "_").split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) or "Generated"
